on:
    push:
      branches:
        - main
  
defaults:
    run:
      working-directory: ./all_in_docker
  
jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set up Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: 16
  
        - name: Install Client Dependencies and Build
          run: |
            cd client
            npm install
            npm run start
  
        - name: Set up Node.js 14 for Server
          uses: actions/setup-node@v3
          with:
            node-version: 14
  
        - name: Install Server Dependencies and Build
          run: |
            cd server
            npm install
            node index.js
  

  
  