on:
    push:
      branches:
        - main
  
defaults:
    run:
      working-directory: ./all_in_docker/client
  
jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
      
        - name: Set up Node.js 14
          uses: actions/setup-node@v3
          with:
            node-version: 14
      
        - name: Install Dependencies and Start
          run: |
            npm install
            npm run start
  