on:
    push:
      branches:
        - main
  
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Set up Node.js 16
          uses: actions/setup-node@v4
          with:
            node-version: 16
  
        - name: Install Dependencies and Build
          working-directory: all_in_docker/client
          run: |
            npm install
            npm run build
  
