on:
    push:
      branches:
        - main
  
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set up Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: 16
  
        - name: Install Dependencies and Start Client in tmux
          run: |
            cd client
            npm install
            tmux new-session -d -s client_session
            tmux send-keys -t client_session 'npm run start' Enter
  
        - name: Set up tmux for Server
          run: |
            sudo apt-get install -y tmux
  
        - name: Run Server in tmux
          run: |
            cd server
            tmux new-session -d -s server_session
            tmux send-keys -t server_session 'npm install' Enter
            tmux send-keys -t server_session 'node index.js' Enter
  
        - name: Wait for Server to Start
          run: sleep 10  # Adjust this wait time as needed
  
        # Continue with additional steps, if necessary
defaults:
  run:
    working-directory: ./all_in_docker/